### ISSUE TITLE
Missing icon or a link

### ISSUE THREAD

**Issue by KonradLinkowski** [StrikingLoo/strikingloo.github.io#23]
Hi,

In this blog post https://strikingloo.github.io/inlining-css there is a sentence:
> Site speed was at ~1.2s per , but I also knew changes in loading speed have superlinear effects on traffic, and don't really have diminishing returns.*

I think there should be something after the `per`.

I checked the [source code](https://github.com/StrikingLoo/strikingloo.github.io/blob/dc25bf0d0bc27d89070bd8426690b44c02e67d26/_posts/2024-03-28-inlining-css.md?plain=1#L15) and there is a `<webpagetest.org>` which doesn't appear at all:
```
 Site speed was at \~1.2s per <webpagetest.org>, but [...]
 ```

**Comment by StrikingLoo** [comment]
That's true, thank you! I just fixed it.
